name: Test (almost) everything
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ruff:
    name: Rough (ruff) linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "./src"
          args: --line-length=120 --select E --select F --select W --select C90 --select UP --select YTT --select ASYNC --select BLE --select B --select A --select COM --select C4 --select DTZ --select T10 --select DJ --select EXE --select FA --select ICN --select G --select PIE --select PYI --select PT --select Q --select RSE --select RET --select SLF --select SLOT --select SIM --select TID --select TCH --select INT --select ERA --select PD --select PGH --select PL --select FLY --select NPY --select AIR --select PERF --select RUF
  build:
    name: Use the Python helper to test (almost) everything
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Execute Python helper with command-line arguments to test (almost) everything
        run: coverage run src/main.py build_image systemd_create systemd_enable systemd_disable podman_reset print_debug_info exit_python_helper && coverage annotate && find . -type f -name "*,cover" -exec cat {} + | awk '/^!/{printf "\033[31m%s\033[0m\n", $0; next} /^>/{printf "\033[32m%s\033[0m\n", $0; next} {print}'
